# Generated by Django 5.2 on 2025-04-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_novapessoa_delete_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novapessoa',
            name='idade',
        ),
        migrations.AddField(
            model_name='novapessoa',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
